/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:079c3d48-e876-41b8-92f3-a4b14319df03",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Pb8dmvZEt",
    "aws_user_pools_web_client_id": "2l6ofo1uq22etk04rl75061m4t",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://exum5fs2zjgbzjnsripnn7dwkm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-az7bo5hiq5fmrjpreupunsyf3q",
    "aws_user_files_s3_bucket": "note7eea8ab924364485811400980c7c248241052-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
